const PACK_INFO = {
  standard: { emoji: '🍻', label: 'Standard', description: 'Pub banter - cheeky but won\'t get you disowned' },
  crazy: { emoji: '🤪', label: 'Unhinged', description: 'Chaotic energy - genuinely absurd scenarios' },
  nsfw: { emoji: '🔞', label: 'NSFW', description: 'Spicy - not for the faint-hearted' },
  custom: { emoji: '✏️', label: 'Custom', description: 'Your group\'s own twisted prompts' },
};

const PROMPT_PACKS = {
  standard: [
    "Most likely to get kicked out of a pub",
    "Most likely to peak in a group chat",
    "Worst taste in music and won't shut up about it",
    "Most likely to start a fight over Monopoly",
    "Biggest drama queen when they're ill",
    "Most likely to reply to their own texts",
    "Most likely to cry at a TV advert",
    "Biggest control freak when ordering food",
    "Most likely to have a breakdown over flat-pack furniture",
    "Most likely to be a terrible liar",
    "Most annoying person to share a bathroom with",
    "Most likely to get way too competitive at a pub quiz",
    "Biggest lightweight pretending they can handle their drink",
    "Most likely to ghost someone mid-conversation",
    "Most likely to peak at school and go downhill from there",
    "Worst at keeping a secret",
    "Most likely to get lost in a car park",
    "Most extra person in the group",
    "Most likely to double text you at 2am",
    "Most likely to fall asleep anywhere after one drink",
    "Most likely to start a petty argument about nothing",
    "Biggest hypocrite in the group",
    "Most likely to throw hands over a parking space",
    "Worst cook who thinks they're Gordon Ramsay",
    "Most likely to have a meltdown at IKEA",
    "Most likely to get banned from a restaurant",
    "Biggest backseat driver",
    "Most likely to spend 3 hours picking a Netflix show",
    "Most likely to cancel plans 10 minutes before",
    "Most likely to talk behind your back and still hug you",
    "Worst morning person - genuinely dangerous before coffee",
    "Most likely to get scammed by an obvious scam",
    "Most likely to argue with a referee on the telly",
    "Most dramatic storyteller - nothing ever just 'happened'",
    "Most likely to bring drama to a children's party",
    "Most likely to eat your leftovers without asking",
    "Biggest gossip who says 'I'm not a gossip'",
    "Most likely to have road rage on a bicycle",
    "Worst dancer who genuinely thinks they can move",
    "Most likely to text something they shouldn't to the wrong group chat",
    "Most likely to cry in a club toilet",
    "Most annoying drunk",
    "Most likely to show up an hour late and blame traffic",
    "Would be the worst flatmate",
    "Most likely to pick a fight with a bouncer",
    "Most likely to accidentally insult someone's mum",
    "Most likely to still bring up something embarrassing from 5 years ago",
    "Most likely to order the most expensive thing then suggest splitting the bill",
    "Most likely to have a midlife crisis at 25",
    "Would be the worst contestant on a dating show",
    "Most likely to drunk-text their ex",
    "Most likely to overshare with a complete stranger"
  ],
  crazy: [
    "Most likely to fight a swan and lose badly",
    "Most likely to accidentally join a cult",
    "Would survive a zombie apocalypse purely by dumb luck",
    "Most likely to get arrested in a foreign country for something stupid",
    "Most likely to try to befriend a bear",
    "Most likely to start a conspiracy theory about themselves",
    "Most likely to eat something they found on public transport",
    "Most likely to get stuck inside something weird and need the fire brigade",
    "Most likely to go viral for all the wrong reasons",
    "Most likely to survive in the wild by eating things that shouldn't be eaten",
    "Most likely to wake up in a different city with no memory of getting there",
    "Most likely to get into a verbal fight with a seagull",
    "Most likely to marry someone they met that day",
    "Most likely to accidentally commit a crime and not realise",
    "Most likely to bring a weapon to a pillow fight",
    "Most likely to be haunted and just accept it",
    "Most likely to get catfished by an AI chatbot and still fall in love",
    "Would be the first to die in a horror film",
    "Would be the last to notice they're in a horror film",
    "Most likely to run a marathon with zero training just because someone dared them",
    "Most likely to be mistaken for a celebrity - the wrong celebrity",
    "Most likely to lick a frozen pole on a dare",
    "Most likely to start a fight with a pigeon",
    "Most likely to get deported for being too weird",
    "Most likely to be abducted by aliens and annoy them into bringing them back",
    "Most likely to show up to a funeral in fancy dress",
    "Most likely to live in a van and call it a lifestyle choice",
    "Most likely to try to fight their own reflection",
    "Most likely to eat a candle because it smelled nice",
    "Most likely to get lost in their own neighbourhood",
    "Most likely to accidentally set something on fire at least once a year",
    "Most likely to be banned from a petting zoo",
    "Most likely to get in trouble for petting a police horse",
    "Most likely to accidentally adopt a wild animal",
    "Most likely to start a religion by accident",
    "Most likely to win a staring contest with a psychopath",
    "Most likely to end up on the news for the dumbest reason",
    "Would cause the most chaos if given control of a country for a day",
    "Most likely to survive the apocalypse purely out of spite",
    "Most likely to challenge a stranger to a duel in 2026",
    "Most likely to be the reason an ambulance gets called at a party",
    "Most likely to try to ride an animal that should absolutely not be ridden",
    "Most likely to eat a bug for less than a fiver"
  ],
  nsfw: [
    "Most likely to shag someone from this group",
    "Biggest liability on a night out",
    "Most likely to have a secret OnlyFans",
    "Most likely to pull at a funeral",
    "Most likely to snog a stranger before midnight on New Year's",
    "Highest body count (and lying about it)",
    "Most likely to send a nude to the wrong person",
    "Most likely to have slept with someone everyone knows about but won't admit",
    "Biggest freak behind closed doors",
    "Most likely to get caught doing something dodgy in public",
    "Most likely to have a wild browser history",
    "Most likely to skinny dip without any encouragement",
    "Most likely to have a hookup they deeply regret",
    "Most likely to flirt with someone's parent",
    "Most likely to sext during a work meeting",
    "Most likely to wake up next to someone and not remember their name",
    "Most likely to hook up in a public toilet",
    "Most likely to have the worst Tinder profile",
    "Most likely to date someone purely for the free dinners",
    "Most likely to have been caught watching something dodgy",
    "Most likely to have a friends-with-benefits that everyone knows about",
    "Most likely to shag someone and pretend it never happened",
    "Most likely to have a one-night stand on holiday and still talk about it",
    "Most likely to flirt their way out of a fine",
    "Most likely to drunkenly confess feelings they definitely don't have sober",
    "Most likely to have a secret they'd die if the group found out",
    "Most likely to cheat at strip poker",
    "Most likely to pull at a wedding",
    "Biggest tease who never follows through",
    "Most likely to have hooked up in a car",
    "Most likely to get caught doing something filthy in a festival tent",
    "Most likely to be secretly freaky behind a wholesome exterior",
    "Most likely to pull on a Tuesday night",
    "Would be the most chaotic on a lads/girls holiday",
    "Most likely to have a walk of shame in broad daylight",
    "Most likely to get with someone way out of their league through sheer audacity",
    "Most likely to have the loudest sex"
  ]
};

const PLACEHOLDER_STARTERS = [
  "Most likely to...",
  "Biggest...",
  "Worst at...",
  "Best at...",
  "Least likely to...",
  "Who would...",
  "Most annoying when...",
  "Secretly...",
  "Would never...",
  "Always...",
];
